### ISSUE TITLE
Wrong number of variables are returned in the test setups

### ISSUE THREAD

**Issue by ismailsenoz** [ReactiveBayes/ExponentialFamilyProjection.jl#13]
`test_convergence_nsamples` returns a single Boolean variable however the following line (https://github.com/ReactiveBayes/ExponentialFamilyProjection.jl/blob/48f78b68a7f949e8b300c7c956ab36b402c4f886/test/projection/projected_to_setuptests.jl#L24) assumes `test_convergence_nsamples` will return two variables. The following test fails however because of the aforementioned problem instead of failing the test throws an error. 

`
    @testset let distribution = Poisson(3.1)
        @test test_projection_convergence(distribution)
    end
`

**Comment by bvdmitri** [comment]
You are right! @Nimrais found this exact issue today as well, he will work on the fix!
