### ISSUE TITLE
Do we really need to have ExponentialFamilyManifolds.jl as dependency? 

### ISSUE THREAD

**Issue by Nimrais** [ReactiveBayes/ExponentialFamilyProjection.jl#24]
However right now, we have a really mild constraints https://github.com/ReactiveBayes/ExponentialFamilyProjection.jl/blob/main/Project.toml#L32 it looks for me that we just do not need it here as dependency.

We use it only in two places

```
get_projected_to_manifold(prj::ProjectedTo) =
    ExponentialFamilyManifolds.get_natural_manifold(
        get_projected_to_type(prj),
        get_projected_to_dims(prj),
        get_projected_to_conditioner(prj),
    )
```

```
function preprocess_initialpoint(
    ::Type{T},
    initialpoint::ExponentialFamilyDistribution{T},
    M,
    parameters,
) where {T}
    return ExponentialFamilyManifolds.partition_point(
        M,
        copy(getnaturalparameters(initialpoint)),
    )
end
```

So maybe it's a reasonable solution is to create `ExponetialManifoldsBase.jl` define these two interfaces there and use `ExponentialFamilyManifolds` only as a test dependency.

**Comment by bvdmitri** [comment]
I don't see this as a problem. Using it in only two places isn't an issue because the library is already small. Creating another Base library doesn't seem to offer any immediate benefits. What specific problem are you aiming to solve?

**Comment by bvdmitri** [comment]
Can be closed?
