### ISSUE TITLE
`extras` keyword is undocumented

### ISSUE THREAD

**Issue by wouterwln** [ReactiveBayes/ExponentialFamilyProjection.jl#36]
In reply to #33 where we add the `extras` keyword. This is currently undocumented. This issue is created because we will probably forget to document it if we don't get reminded.

**Comment by bvdmitri** [comment]
Why? I see the documentation has been added here https://github.com/ReactiveBayes/ExponentialFamilyProjection.jl/pull/33/commits/32cb64a00c418750704e283b1a36609e9d2d4026

**Comment by wouterwln** [comment]
I think we should add a section in the documentation as well  @ https://reactivebayes.github.io/ExponentialFamilyProjection.jl/stable/

**Comment by wouterwln** [comment]
Ah nevermind, it's there
