### ISSUE TITLE
Referring to this package from Manopt.jl

### ISSUE THREAD

**Issue by kellertuer** [ReactiveBayes/ExponentialFamilyProjection.jl#37]
In the recent release of Manopt.jl, I started a small section on the about page

https://manoptjl.org/stable/about/

about packages using Manopt. I hope it is ok that I liste you – if you want to extend on the entry and make it a bit longer, that is very welcome :)
(this is not an issue per se, more a discussion point – and thanks for using Manopt!)

**Comment by ismailsenoz** [comment]
We are quite happy with being listed and also quite happy with Manopt.jl. Thanks for such a great package.
